---
title: "Untitled"
author: "Kiera Matiska"
date: "1/31/2022"
output: html_document
---

# Overview:


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# attach packages
library(tidyverse)
library(here)
library(GGally)
library(AICcmodavg)
library(broom)
library(caret)
library(jtools)
```

## Read in Data

```{r}
palmetto <- read_csv("palmetto.csv")
```

## Wrangle and Visualize Data {.tabset .tabset-fade}

Create a new data set with the species name in replace of 1 and 2 in species column

```{r}
palmetto_species <- palmetto %>% 
  mutate(species = case_when(
    species == "1" ~ "Serenoa repens",
    species == "2" ~ "Sabal Etonia"
  ))
```

Use `ggpairs` to compare data

```{r}
palmetto_species %>% 
  select(species, height:green_lvs) %>% 
  ggpairs(aes(color = species))
```

Create a subset with only:

- species
- height
- canopy length
- canopy width
- green leaves

```{r}
palmetto_subset <- palmetto_species %>% 
  select(species, height:green_lvs) %>% 
  drop_na()
```

### Plot 1

```{r}
ggplot(data = palmetto_subset,
       aes(x = height)) +
  geom_histogram(bins = 20, fill = "darkolivegreen4", color = "darkolivegreen") +
  facet_wrap(~ species) +
  labs(title = "Number of Individuals of Two Palmetto\nSpecies Within Different Height Classes",
       x = "Height (cm)",
       y = "Number of Individuals") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.background = element_rect(fill = "aliceblue"))
```

### Plot 2

```{r}
ggplot(data = palmetto_subset,
       aes(x = species, y = green_lvs)) +
  geom_boxplot(color = "black") +
  labs(title = "Number of Green Leaves \nBetween Two Palmetto Species",
       x = "Species",
       y = "Count of Green Leaves") +
  theme_gray() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.background = element_rect(fill = "aliceblue"))
```

### Plot 3

```{r}
ggplot(data = palmetto_subset,
       aes(x = height, y = width)) +
  geom_point(aes(color = green_lvs)) +
  facet_wrap(~ species) +
  labs(title = "Maximum Height vs. Width")
  
```











