---
title: "Untitled"
author: "Kiera Matiska"
date: "2/5/2022"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# attach packages
library(tidyverse)
library(kableExtra)
library(equatiomatic)
```

## Read in data

```{r}
lizards <- read_csv("lizard.csv") %>% # read in csv
  mutate(sex = case_when(
    sex == "M" ~ "male",
    sex == "F" ~ "female"
  ))
```

## Start nonlinear Least Square Model

W = a*SVL^b

- W = weight
- SVL = snout to vent length
- a and b are the parameters needed to be fit

### Wrangle data

```{r}
# add some log columns of the data: length and width
lizards_log <- lizards %>% 
  mutate(log_length = log(SV_length)) %>% 
  mutate(log_weight = log(weight)) %>% 
  drop_na() # drop na values

lizards_model_guess <- lm(log_weight ~ log_length, data = lizards_log) # create a guess model using log values
lizards_model_guess

conceptual_model <- function(a, SV_length, b) { # define the conceptual model
  W = a * SV_length ^ b
  return(W)
}

new_model <- function (a, SV_length, b) { # define the linear equation model
  ln(W) = b * ln(a) + b * ln(SV_length)
  print(W)
}

guess_coef <- coefficients(lizards_model_guess) # find the coefficients
guess_coef
```

### Write NLS model

```{r}
nls_lizards <- nls(weight ~ conceptual_model(a, SV_length, b),
                   data = lizards,
                   start = list(a = 2.718^(guess_coef[1]/guess_coef[2]),
                                b = guess_coef[2]),
                   trace = TRUE)
nls_lizards
```

### Model Visualization

```{r}
ggplot(data = lizards,
       aes(x = SV_length, y = weight)) +
  geom_point(aes(color = sex),
             size = 0.7,
             curve(nls_lizards, a = 2.718^(guess_coef[1]/guess_coef[2]),
                   b = guess_coef[2])) +
  labs(title = "Nonlinear Least Squares Model Comparing Lizard\nSnout to Vent Length to Weight by Sex",
        x = "Snout to Vent Length (mm)",
        y = "Weight (g)") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.background = element_rect(fill = "aliceblue"))
```

### Model Western Whiptail Lizard

```{r}
# CNTI is Western Whiptail
lizards_
```

